/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nclock;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import java.util.*;

public class App extends JFrame {
    Calendar calendar;
    SimpleDateFormat timeF;
    SimpleDateFormat dayF;
    SimpleDateFormat dateF;
    JLabel timeL;
    JLabel dayL;
    JLabel dateL;
    String time;
    String day;
    String date;

    App() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Digital NClock");
        this.setLayout(new FlowLayout());
        this.setSize(500, 200);
        this.setResizable(false);
        timeF = new SimpleDateFormat("hh:mm:ss a");
        dayF = new SimpleDateFormat("EEEE ");
        dateF = new SimpleDateFormat("dd MMM, yyyy");

        timeL = new JLabel();
        timeL.setForeground(Color.RED);
        timeL.setFont(new Font("Verdana", Font.PLAIN, 64));

        dayL = new JLabel();
        dayL.setFont(new Font("Ink Free", Font.PLAIN, 32));

        dateL = new JLabel();
        dateL.setFont(new Font("Ink Free", Font.PLAIN, 30));

        this.add(timeL);
        this.add(dayL);
        this.add(dateL);
        this.setVisible(true);
        
        setClock();
    }

    public void setClock() {
        while (true) {
            time = timeF.format(Calendar.getInstance().getTime());
            timeL.setText(time);

            day = dayF.format(Calendar.getInstance().getTime());
            dayL.setText(day);

            date = dateF.format(Calendar.getInstance().getTime());
            dateL.setText(date);

            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.getStackTrace();
            }
        }
    }
    public static void main(String[] args) {
        new App();
    }
}