/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nclock;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import java.util.*;
import java.io.*;
import java.util.*;

public class App extends JFrame {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
